kaito-project/kaito

.github/workflows/tests.yml, README.md
- Add codcov secret to the Unit test pipeline
- Add codcov badge to the Readme
=> ci: Support codcov

pkg/controllers/workspace_controller_test.go
=> style: Run gofmt

.github/workflows/e2e-preset-test.yml, .github/workflows/preset-image-build.yml
Disable briefly while transitioning to new folder structure and VM
=> ci: temp disable building new images

api/v1alpha1/workspace_validation.go, api/v1alpha1/workspace_validation_test.go
This PR updates the crd validation UT to use the test model.
=> chore: Refactor to implement model plugin - part 5

.github/workflows/kind-cluster/main.py, presets/models/falcon/inference-api.py
PR addresses: 
1. VM disk ran out of space so models have been moved to another attached disk
2. Timeout added
3. Filepaths and permissions updated in relation to the github runner location/user
=> ci: trigger preset image build

.github/workflows/preset-image-build.yml
Changes in .md files should not trigger rebuild images pipeline
=> feat: ignore doc changes in build pipeline

.gitignore, README.md
Some Azure CLI command cleanup and update Helm chart installation instructions to use a values.override.yaml file as some may run into inconsistent results using `yq` to modify values.yaml file in place.
=> docs: update install instructions

README.md
Hello Azure team,
This PR contains a minor grammar suggestion for you to consider.
Best regards,
David
=> A minor grammar suggestion

.github/workflows/e2e-preset-configs.json, .github/workflows/e2e-preset-test.yml, .github/workflows/preset-image-build.yml, presets/models/supported_models.yaml
Prevents crash, if ACR Image doesn't exist.
=> fix: Minor Fix in e2e preset pipeline - Checking ACR Image

docs/proposals/20240205-mistral-instruct.md
Proposal for Mistral 7B Instruct
=> feat: Add Mistral 7b Instruct

docs/proposals/20240205-mistral.md
=> feat: Mistral 7B Proposal

docs/proposals/20240206-phi-2.md
Proposal for adding microsoft/phi-2
=> feat: phi-2 proposal

.github/workflows/e2e-preset-test.yml, .github/workflows/preset-image-build.yml
1. BRANCH_NAME works for every trigger that you can specify under on
2. Fix format of the combined matrix
3. Increase default timeout for resource (dep or statefulset) creation
=> fix: Minor build and e2e workflow fixes

docker/presets/llama-2/Dockerfile
Fix llama dockerfile for new base image
=> fix: Update llama dockerfile

.github/workflows/kaito-e2e.yaml, test/e2e/preset_test.go
Add image secret for test repo
=> feat: Add Image Pull Secret

.github/workflows/build-publish-image.yml, .github/workflows/create-release.yml, .github/workflows/kaito-e2e.yaml, .github/workflows/publish-image-acr.yml, Makefile
=> ci: Add scan trivy step to publish image pipeline

presets/models/supported_models.yaml
=> fix: Add release history comments

Makefile, README.md, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml
e2e for new image passed: https://github.com/Azure/kaito/actions/runs/8119543799/job/22195551139
=> release: update manifest and helm charts for v0.2.0

README.md
Correct the mail list name.
Fix issue #314
=> docs: Update README.md to correct the mail list

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/report_bug.md, .github/PULL_REQUEST_TEMPLATE.md
- Add report bug template
- Add feature request template
- Add PR template
=> chore: Add GitHub issue/PR templates

pkg/controllers/workspace_controller.go
Address some missing needed nil checks in workspace controller
=> fix: Add preset nil checks

api/v1alpha1/workspace_validation_test.go
Couple UTs added
- [ x] added unit tests and e2e tests (if applicable).
=> test: Add UTs for invalid image source or destination

examples/kaito-karpenter-noodepool.yaml
Add an example for `Karpenter` cloud provider `NodePool` for Azure.
=> feat: Add Karpenter Azure cloud provider NodePool

docs/installation.md
Update the installation doc with the new namespace and add 'jq' as necessary tool to be installed
=> docs: Update namespace patch and dependency for installation.md

.github/workflows/codeql.yml
=> ci: fix codeql error due to golang version 1.22

.github/workflows/codeql.yml
=> ci: fix codeQL action version

.github/workflows/codeql.yml
=> ci: bump codeQL to V3

.github/workflows/codeql.yml
=> ci: add setup-go GH action and codeQL analysis category

.github/dependabot.yml
Dependabot alerts upon security needed updates
=> fix: Update dependabot.yml for security updates

pkg/model/interface.go, pkg/tuning/preset-tuning.go, pkg/tuning/preset-tuning_test.go, presets/models/falcon/model.go
1. Add interface field `TuningMethodGPUMemory` - Min GPU memory per tuning method (batch size 1).
2. Fix bug(s) in tuning ConfigMap creation
=> feat: Add Min GPU Memory Requirement

Makefile, charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
Fix the Makefile to copy crd to chart whenever it is updated. The changes in CRD are comment format changes.
=> chore: Copy latest CRD to chart

api/v1alpha1/params_validation.go, api/v1alpha1/workspace_validation_test.go, api/v1alpha1/zz_generated.deepcopy.go, charts/kaito/workspace/templates/lora-params.yaml, charts/kaito/workspace/templates/qlora-params.yaml, presets/tuning/text-generation/cli.py, presets/tuning/text-generation/dataset.py, presets/tuning/text-generation/fine_tuning.py, presets/tuning/text-generation/parser.py
Expected data format
```
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "Paris, as if everyone doesn't know that already."}]}
```
=> fix: Standardize Dataset Input

pkg/tuning/preset-tuning.go
Adapter Base Image to Include Basic Utilities
=> fix: Adapter Base Image to Include Basic Utilities

docs/tuning/README.md, presets/tuning/README.md
=> docs: Add Tuning API Documentation

Makefile, api/v1alpha1/workspace_validation.go, api/v1alpha1/workspace_validation_test.go
Tuning Resource Validation Check
=> feat: Tuning Resource Validation Check

.github/workflows/e2e-preset-test.yml, .github/workflows/kind-cluster/determine_models.py, presets/test/manifests/phi-3-medium-128k-instruct/phi-3-medium-128k-instruct-service.yaml, presets/test/manifests/phi-3-medium-128k-instruct/phi-3-medium-128k-instruct.yaml, presets/test/manifests/phi-3-medium-4k-instruct/phi-3-medium-4k-instruct-service.yaml, presets/test/manifests/phi-3-medium-4k-instruct/phi-3-medium-4k-instruct.yaml, presets/test/manifests/phi-3-small-128k-instruct/phi-3-small-128k-instruct-service.yaml, presets/test/manifests/phi-3-small-128k-instruct/phi-3-small-128k-instruct.yaml, presets/test/manifests/phi-3-small-8k-instruct/phi-3-small-8k-instruct-service.yaml, presets/test/manifests/phi-3-small-8k-instruct/phi-3-small-8k-instruct.yaml
Adds Phi-3 manifests and allows us to run e2e for just Phi-3 Models
=> feat: Add Phi-3 Manifests and Custom E2E Run Flag

.github/workflows/kind-cluster/main.py, presets/models/falcon/model.go, presets/models/mistral/model.go, presets/models/phi2/model.go, test/e2e/preset_test.go, test/e2e/utils/utils.go
Bump the image preset plugins tags
=> fix: Bump plugins tags

.github/actions/build-image-action/action.yml, .github/workflows/kind-cluster/main.py, .github/workflows/preset-image-build-1ES.yml, .github/workflows/preset-image-build.yml, presets/inference/text-generation/requirements.txt, presets/models/mistral/model.go, presets/models/supported_models.yaml, presets/test/manifests/mistral-7b/mistral-7b.yaml, presets/tuning/text-generation/requirements.txt, test/e2e/preset_test.go
Update model version and Address missing weights files fix
=> fix: Update Mistral Version and Rebuild

Makefile, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml
release: update manifest and helm charts for v0.3.0
=> release: update manifest and helm charts for v0.3.0

.github/workflows/e2e-workflow.yml, Makefile, test/e2e/inference_with_adapters.go
=> chore: Change adapter image to temp ACR registry for e2e test

pkg/tuning/preset-tuning.go
=> fix: Add retry logic for data downloader

README.md
=> chore: edit README to announce new release

presets/README.md
=> chore: Add Phi-3 Link to README.md

README.md, docs/inference/README.md
Add docs to show how to inference models, add examples for models with adapters
=> docs: add doc for inference

test/e2e/inference_with_adapters.go, test/e2e/preset_test.go, test/e2e/utils/utils.go
Add fail logs for inference with adapter test
=> fix: Add Fail logs for Inference w/ Adapter test

docs/tuning/README.md
Update README.md with additional details on tuning time calculation
=> fix: Update README.md with additional details on tuning time calculation

presets/models/mistral/model.go, presets/models/phi2/model.go, presets/models/phi3/README.md, presets/models/phi3/model.go
=> feat: Update README.md to add Phi-Medium

README.md
Add faq question for `How do I ensure preferred nodes are correctly labeled for use in my workspace?`
=> chore: FAQ Question on PreferredNodes addition

presets/inference/text-generation/inference_api.py
Add adapter logs for Inference API
=> feat: Add adapter logs for Inference API

presets/inference/text-generation/requirements.txt, presets/models/supported_models.yaml, presets/tuning/text-generation/requirements.txt
PR serves to trigger the build pipeline to update preset model images.
=> feat: Update Preset Model Tags

presets/models/falcon/model.go, presets/models/mistral/model.go, presets/models/phi2/model.go, presets/models/phi3/model.go
Update the Preset Image tags used by Kaito Controller
=> feat: Update Preset Model Tags for Release

Makefile, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml
=> release: Update manifest and helm charts for v0.3.1

README.md
=> docs: Update README with the new release

.github/workflows/kaito-e2e.yml
Prevent auto run of az-karpenter while its WIP
=> fix: Update kaito-e2e.yml

pkg/controllers/ragengine_status.go, pkg/controllers/ragengine_status_test.go, pkg/controllers/workspace_controller.go, pkg/controllers/workspace_status.go, pkg/controllers/workspace_status_test.go
refact updateStatusConditionIfNotMatch for both RAG and workspace
=> feat: refact updateStatusConditionIfNotMatch for both RAG and workspace

pkg/controllers/ragengine_status.go, pkg/controllers/ragengine_status_test.go, pkg/controllers/workspace_controller.go, pkg/controllers/workspace_status.go, pkg/controllers/workspace_status_test.go
Revert the refactoring of RAGEngineStatus and WorkspaceStatus
=> feat: Revert the refactoring of RAGEngineStatus and WorkspaceStatus

presets/test/falcon-benchmark/README.md
Commit 498f92bd0b0de73716cabb9fc4920ffe51900863 changed the location of the `tfs/Dockerfile`. This PR adjusts sources to changes.
=> fix: update Dockerfile

.github/workflows/e2e-workflow.yml, .github/workflows/kaito-e2e.yml
=> Revert "feat: Migrate E2E pipeline to using Self-Hosted Runner"

charts/DemoUI/inference/values.yaml
=> fix: polish liveness health threshold

docs/custom-model-integration/Dockerfile.reference
=> fix: Update Dockerfile.reference

LICENSE, README.md
**Reason for Change**: reflected CoC changes, removed Microsoft trademarks, updated contributions for KAITO CNCF onboarding
=> chore: removed Microsoft trademark, updated contributing guidelines, CoC in readme

pkg/ragengine/services/requirements.txt, pkg/ragengine/services/tests/vector_store/test_base_store.py, pkg/ragengine/services/tests/vector_store/test_chromadb_store.py, pkg/ragengine/services/tests/vector_store/test_faiss_store.py, pkg/ragengine/services/vector_store/chromadb_store.py
Introduce abstract class for testing new integrations with ChromaDB as the first example.
=> feat: Introduce Abstract Class for Integration Testing

hack/runner/install_tools.sh
Script for setting up a new runner on a VM
=> feat: Runner Setup Script

.github/workflows/e2e-workflow.yml
=> fix: Add K8s Env Var

.github/workflows/e2e-workflow.yml, .github/workflows/kaito-e2e.yml
Ensure Specified K8s Version Used
=> fix: Remove empty var

api/v1alpha1/labels.go, pkg/ragengine/controllers/ragengine_controller.go, pkg/ragengine/controllers/ragengine_controller_test.go, pkg/utils/test/testUtils.go, pkg/workspace/controllers/workspace_controller.go
RAG engine controller revision
=> feat: RAG engine controller revision

Makefile
=> fix: Update Makefile

.github/workflows/publish-gh-image.yml, .github/workflows/publish-mcr-image.yml
fix: remove secret env when trigger e2e flow
=> fix: remove secret env when trigger e2e flow

pkg/ragengine/controllers/preset-rag.go, pkg/ragengine/services/main.py, pkg/ragengine/services/models.py, pkg/workspace/inference/preset-inferences.go
=> feat: RAG service health check

docker/ragengine/service/Dockerfile
Change the Copy path of RAGEngine Docker file
=> fix: patch of RAGengine dockerfile

.github/workflows/e2e-workflow.yml
=> fix: Update Runner Labels

docs/custom-model-integration/Dockerfile.reference
Update baseimage and rebuild reference image in packages
=> feat: Custom Dockerfile update BaseImage

.github/workflows/kind-cluster/determine_models.py, .github/workflows/kind-cluster/main.py, .github/workflows/preset-image-build-1ES.yml
We introduce workflow dispatch flag for running just the public models on 1ES machine
=> feat: Add flag for running 1ES Public Models

docs/installation.md
Remove unused variable in docs/installation.md (https://github.com/kaito-project/kaito/issues/723)
=> docs: Update installation.md

.github/e2e-preset-configs.json, .github/workflows/e2e-preset-tuning-test.yml, presets/workspace/test/tuning/tuning-job.yaml
fix preset tuning test workflow
=> fix: preset tuning test workflow

Makefile, presets/ragengine/vector_store/chromadb_store.py
ChromaDB has been updated 0.5.18->0.6.1. Fix addresses slight library changes.
=> fix: Update RAG ChromaDB UTs v0.6.1

Makefile, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, docs/installation.md
make a release for kaito v0.4.2
=> release: update manifest and helm charts for v0.4.2

presets/ragengine/main.py
Minimal changes required for ensuring rag engine image doesn't fail
=> fix: Prevent blocking healthcheck during Inference

.github/workflows/e2e-base-setup.yaml, .github/workflows/e2e-workflow.yml, Makefile
add an e2e base setup file for the duplicate part
=> chore: Reorg e2e test code to be reused in RAG e2e tests

presets/workspace/inference/chat_templates/deepseek-r1-distill-llama-8b.jinja, presets/workspace/inference/chat_templates/deepseek-r1-distill-qwen-14b.jinja, presets/workspace/models/supported_models.yaml
=> feat: Add Deepseek Model

presets/workspace/models/deepseek/model.go, test/e2e/preset_test.go, test/e2e/preset_vllm_test.go
=> feat: Add DeepSeek Model for E2E

examples/inference/kaito_workspace_deepseek_r1_distill_llama_8b.yaml, examples/inference/kaito_workspace_deepseek_r1_distill_qwen_14b.yaml, presets/workspace/models/deepseek/README.md
Add DeepSeek READMEs and Example
=> feat: Add DeepSeek READMEs and Example

Makefile, README.md, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, docs/installation.md
Update manifest and helm charts for v0.4.3
=> release: update manifest and helm charts for v0.4.3

.github/workflows/e2e-base-setup.yaml, .github/workflows/e2e-workflow.yml
=> fix: use ghcr image for e2e test during release

README.md
Noticed a spelling mistake when going through the readme, figured I would fix it :-) 
=> Fix spelling mistake in Readme

test/rage2e/rag_test.go
=> chore: RAG e2e test with Kaito vllm inference

test/rage2e/rag_test.go
=> chore: RAG E2E test index and query validation

presets/ragengine/inference/inference.py
Refactored the Inference class to use fully asynchronous HTTP requests with httpx, ensuring non-blocking execution. Replaced synchronous requests calls with async def _async_post_request(...)
=> feat: Make Inference Class Fully Async with HTTPX Requests

presets/ragengine/inference/inference.py, presets/ragengine/main.py, presets/ragengine/models.py, presets/ragengine/requirements-test.txt, presets/ragengine/tests/api/conftest.py, presets/ragengine/tests/api/test_main.py, presets/ragengine/tests/vector_store/test_base_store.py, presets/ragengine/vector_store/base.py, presets/ragengine/vector_store_manager/manager.py
Overview
This PR addresses several issues discovered in the LLMRerank flow and HTTPx-based asynchronous client usage. 
1. LLMRerank Library Inconsistencies
- Problem: When the LLM produces a format that LLMRerank can’t parse, LLMRerank returns an empty response or an empty node list, resulting in a frustrating user experience. Solution: Adjust the VLLM output format so LLMRerank properly parses and handles the responses, preventing empty or “unparsable” results.
2. HTTPx Timeout Leading to Confusing 500 Errors
- Problem: The default 5-second timeout in HTTPx is too short for certain requests, causing unexpected 500 errors in async environments. Solution: Increase the timeout and make it configurable so that long-running requests can complete without prematurely …
=> fix: LLMRerank edge cases, HTTPx timeout issues, and async client segfaults

presets/ragengine/config.py, presets/ragengine/main.py, presets/ragengine/tests/api/test_main.py, presets/ragengine/tests/vector_store/test_base_store.py, presets/ragengine/vector_store/base.py, presets/ragengine/vector_store_manager/manager.py
Add endpoint for persisting index
=> feat: Add Persist Index Endpoint

presets/ragengine/vector_store/base.py
Add RWLock for persist function
=> feat: Add Persist RWLock

presets/ragengine/inference/inference.py
Switch to use prompt format as we do single-turn query 
https://huggingface.co/docs/text-generation-inference/en/reference/api_reference
=> fix: Huggingface Request Format

presets/ragengine/inference/inference.py
This change addresses the runtime error that occurs when calling asyncio.run() from within an already running event loop in the LLMRerank callback. 
Previously, the synchronous complete() function attempted to run the asynchronous acomplete() via asyncio.run(), which led to conflicts and errors in contexts where an event loop was already active.
Llamaindex should fix this - it isn't a hard fix, I will take a look.
=> feat: Offload Async Coroutine Execution to Separate Thread to Avoid Nested Event Loop Error

pkg/ragengine/controllers/preset-rag.go, pkg/ragengine/controllers/preset-rag_test.go, presets/ragengine/main.py, test/rage2e/rag_test.go
Add load and persist endpoints tests to RAGEngine E2E
=> feat: Add load and persist endpoints tests to RAGEngine E2E

docs/installation.md
Add yq dependency to install instructions
=> fix: Add yq dependency to install instructions

docs/custom-model-integration/custom-deployment-template.yaml, docs/custom-model-integration/reference-image-deployment.yaml
Fixes #931 " 
___
enhancement
___
Added health check probe for the deployment yaml used by custom-model-integration.
=> feat: add probes to template sample

README.md
=> Update README.md for RAG coming soon

pkg/workspace/manifests/manifests.go, presets/workspace/models/qwen/model.go
Set the PyTorch CUDA memory allocation configuration to use expandable segments for better memory management.
=> feat: Add Pytorch Expandable segments envvar

docs/custom-model-integration/reference-image-deployment.yaml
=> docs: Update reference-image-deployment.yaml

docs/proposals/20241212-phi4-instruct.md
Fixes: https://github.com/kaito-project/kaito/issues/790
=> Add proposal for phi-4 model

pkg/model/interface.go, pkg/utils/test/testModel.go, pkg/workspace/inference/preset-inferences.go, pkg/workspace/inference/preset-inferences_test.go
Code refactoring to improve readability. Following the suggestions provided by copilot. 
This change also fixes UT to initialize parameter maps.  
Fix a UT bug: we need to clear the adapters when the test does not need them.
=> chore: refactor interface.go

presets/workspace/models/deepseek/model.go, test/e2e/preset_vllm_test.go
now allow tensor parallel
Fixes #899 
=> feat: enable reasoning output for deepseek model

presets/workspace/models/falcon/model.go, presets/workspace/models/phi2/model.go
Reverts kaito-project/kaito#1015
=> Revert "feat: Provide default chat templates for Falcon and Phi-2 fine-tuning"

Makefile, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, docs/installation.md
=> release: update manifest and helm charts for v0.4.5

.github/workflows/e2e-workflow.yml
add registry into release pipeline
=> fix: add registry into release pipeline (#1026)

.github/workflows/e2e-workflow.yml, docs/controller-metrics/kaito-workspace_controller_metrics.md
doc for workspace controller metrics
=> chore: doc for workspace controller metrics

presets/README.md
=> feat: Update README.md

docker/presets/models/llama-2/Dockerfile, docker/presets/models/tfs/Dockerfile, docker/ragengine/service/Dockerfile
Ensure latest security patches applied to debian packages
Example of perl CVE
```
Getting Scan Status.
....Scan results are available
┌─────────┬──────────────────────────────────────────────────────────────┐
│ QID     │ Details                                                      │
├─────────┼──────────────────────────────────────────────────────────────┤
│         │ Signature: VULNSIGS-VM-2.6.305.3-2                           │
│         │ Manifest: 2.6.305-3                                          │
│         │                                                              │
│ 6019624 │ Debian Security Update for perl (CVE-2024-56406)             │
│         │ http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-56406 │
│         │ Risk: HIGH - CVSS: 8.6 …
```
=> feat: Ensure latest security patches applied on debian packages

docs/RAG/README.md, examples/RAG/kaito_ragengine_phi_3.yaml
update RAG doc and exmaple yaml files for avoiding conflicts
=> chore: update RAG doc for avoiding conflicts

pkg/ragengine/controllers/ragengine_controller.go, pkg/utils/nodeclaim/nodeclaim.go, pkg/utils/nodeclaim/nodeclaim_test.go, pkg/utils/resources/nodes.go, pkg/workspace/controllers/workspace_controller.go
chore: avoid using goto by using retry.OnError
=> chore: avoid using goto by using retry.OnError

pkg/ragengine/controllers/preset-rag.go, pkg/ragengine/controllers/ragengine_controller.go, pkg/ragengine/manifests/manifests.go, pkg/ragengine/manifests/manifests_test.go, pkg/utils/test/testUtils.go, pkg/workspace/controllers/workspace_controller.go, pkg/workspace/inference/preset-inferences.go, pkg/workspace/inference/template_inference.go, pkg/workspace/manifests/manifests.go, pkg/workspace/manifests/manifests_test.go, pkg/workspace/tuning/preset-tuning.go
chore: clean up the code and add ut for generating manifests
=> chore: simplify the manifests generation code and add ut

pkg/utils/nodeclaim/nodeclaim.go
=> fix: change ephemeral storage to resource storage in nodeclaim

docs/tuning/README.md
Add troubleshooting section for Target Modules error
=> fix: Troubleshooting Target Modules Error

.github/workflows/markdown-link-check.yml, CODE_OF_CONDUCT.md, README.md, docs/proposals/20250325-distributed-inference.md, hack/go-install.sh
Add proposal for distributed inference. Draft implementation can be found in #949.
Related to #912 
=> docs: add proposal for distributed inference

pkg/ragengine/controllers/preset-rag.go, pkg/utils/common-preset.go, pkg/workspace/controllers/workspace_controller.go, pkg/workspace/inference/preset-inferences.go, pkg/workspace/tuning/preset-tuning.go
=> feat: Ensure shm volume added

presets/workspace/inference/chat_templates/tool-chat-hermes.jinja, presets/workspace/inference/chat_templates/tool-chat-llama3.1-json.jinja, presets/workspace/inference/chat_templates/tool-chat-mistral.jinja, presets/workspace/inference/chat_templates/tool-chat-phi4-mini.jinja
chat template for tool calling support
=> chore: update tool chat templates

.github/workflows/e2e-workflow.yml, .github/workflows/workspace-e2e.yml, presets/workspace/models/llama3/model.go, test/e2e/preset_test.go, test/e2e/preset_vllm_test.go, test/e2e/utils/utils.go, test/e2e/webhook_test.go, test/rage2e/rag_test.go
Add E2E test for new Llama Model
=> test: Add E2E test for new Llama Model

docs/kaito-oom-prevention.md, pkg/workspace/inference/preset-inferences_test.go, pkg/workspace/manifests/manifests.go
fix: remove PYTORCH_CUDA_ALLOC_CONF environment variable
Fixes #1077 
=> fix: remove PYTORCH_CUDA_ALLOC_CONF environment variable

Makefile, README.md, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, docs/installation.md, terraform/variables.tf
release: update manifest and helm charts for v0.4.6
=> release: update manifest and helm charts for v0.4.6

GOVERNANCE.md
This PR introduces a written, open governance page for KAITO and is subject to change as the project grows in scope and usage.
=> Intro project governance page

.github/e2e-preset-configs.json, .github/workflows/e2e-preset-test.yml, .github/workflows/e2e-preset-tuning-test.yml, presets/workspace/models/supported_models.yaml, presets/workspace/test/manifests/vllm-distributed/vllm-distributed.yaml
=> feat: bump base image to 0.0.3

examples/fine-tuning/kaito_configmap_tuning_phi_3.yaml
Add an example for phi_3 configuration for fine tuning
=> chore: Create kaito_configmap_tuning_phi_3.yaml

api/v1alpha1/workspace_validation.go, api/v1alpha1/workspace_validation_test.go, api/v1beta1/workspace_validation.go, api/v1beta1/workspace_validation_test.go, test/e2e/preset_test.go, test/e2e/utils/utils.go
test: add support volume for tuning e2e
add e2e for pr:https://github.com/kaito-project/kaito/pull/1118
=> test: add support volume for tuning e2e

website/docs/presets.md
=> docs: fix broken links for presets

charts/kaito/artifacthub-repo.yml
Created artifacthub-repo.yml to publish to artifacthub
=> feat: Create artifacthub-repo.yml

Makefile, README.md, charts/kaito/ragengine/Chart.yaml, charts/kaito/ragengine/README.md, charts/kaito/ragengine/values.yaml, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, terraform/variables.tf, website/docs/installation.md
=> release: update manifest and helm charts for v0.5.0

.github/workflows/publish-ragengine-helm-chart.yml, .github/workflows/publish-workspace-helm-chart.yml, .github/workflows/ragengine-e2e-workflow.yml
=> fix: specify helm charts target in pipeline

README.md, examples/inference/kaito_workspace_llama-3.3_70b_instruct.yaml, website/docs/intro.md, website/docs/proposals/20250529-llama-3.3-70b-instruct.md
=> docs: add explanation for max-model-len requirement

.github/workflows/deploy-docs.yml
=> fix: fix deploy-docs.yml

README.md
Update to readme and reorganization of "Get Involved" section
=> docs: Update README.md with meeting notes link

Makefile, README.md, charts/kaito/ragengine/Chart.yaml, charts/kaito/ragengine/README.md, charts/kaito/ragengine/values.yaml, charts/kaito/workspace/Chart.yaml, charts/kaito/workspace/README.md, charts/kaito/workspace/values.yaml, terraform/variables.tf, website/docs/installation.md, website/docs/intro.md
release: update manifest and helm charts for v0.5.1
=> release: update manifest and helm charts for v0.5.1

Makefile
Running `make help` now searches for all make targets with a doc comment and produces the following output.
```
Usage:
make <target>
Development
manifests                  Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
generate                   Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
unit-test                  Run unit tests.
create-rg                  Create resource group
create-acr                 Create test ACR
create-aks-cluster         Create test AKS cluster (with msi, oidc, and workload identity enabled)
create-aks-cluster-with-kaito  Create test AKS cluster (with msi, oidc and kaito enabled)
create-aks-cluster-for-karpenter  Create test AKS cluster (with msi, cilium, …
```
=> feat: add `make help` target to Makefile

website/docs/proposals/20250611-workspace-subresource-scale-api.md, website/docs/proposals/20250704-keda-scaler-for-inference-workloads.md
=> fix: image link error in scaler proposals

.github/actions/e2e-base-setup/action.yml, .github/workflows/e2e-workflow.yml, .github/workflows/ragengine-e2e-workflow.yml, .github/workflows/ragengine-e2e.yml, Makefile, pkg/sku/azure_sku_handler.go, test/e2e/preset_test.go, test/e2e/preset_vllm_test.go, test/rage2e/rag_test.go
=> chore: update node sku for e2e tests

presets/workspace/dependencies/requirements.txt
fix: add missing pynvml package dependency introduced by https://github.com/kaito-project/kaito/pull/1405
=> fix: add missing pynvml package dependency

website/docs/aikit.md, website/versioned_docs/version-v0.6.x/aikit.md
=> docs: update aikit docs to fix links

charts/kaito/workspace/templates/supported-models-configmap.yaml, presets/workspace/models/supported_models.yaml
chore: bump kaito-base tag to 0.0.7 for https://github.com/kaito-project/kaito/pull/1448
=> chore: bump kaito-base tag to 0.0.7

.github/dependabot.yaml
ci: update .github/dependabot.yaml with the right file paths
=> ci: update .github/dependabot.yaml with the right file paths

examples/gateway-api-inference-extension/destinationrule-mistral-7b-instruct.yaml, examples/gateway-api-inference-extension/destinationrule-phi-4-mini-instruct.yaml, examples/gateway-api-inference-extension/gateway.yaml, examples/gateway-api-inference-extension/httproute-bbr.yaml, examples/gateway-api-inference-extension/httproute.yaml, website/docs/gateway-api-inference-extension.md, website/sidebars.js
docs: add docs for Gateway API Inference Extension
=> docs: add docs for Gateway API Inference Extension

website/docs/gpu-benchmarks.md
=> docs: add links and note to GPU benchmarks doc

docs/proposals/20250820-byo-nodes.md
=> docs: add BYO nodes redesign proposal

docs/proposals/20250820-byo-nodes.md
=> docs: add implementation strategy for BYO nodes proposal

Makefile, README.md, api/v1alpha1/doc.go, api/v1alpha1/labels.go, api/v1beta1/labels.go, charts/kaito/ragengine/values.yaml, charts/kaito/workspace/values.yaml, docs/documentation-versioning.md, docs/proposals/20250611-workspace-subresource-scale-api.md, docs/proposals/20250630-kaito-cli.md, examples/custom-model-integration/Dockerfile.reference, examples/custom-model-integration/reference-image-deployment.yaml, pkg/featuregates/featuregates.go, pkg/model/interface.go, pkg/utils/plugin/plugin.go, test/e2e/inference_with_adapters_test.go, test/e2e/preset_test.go, test/e2e/preset_vllm_test.go, test/rage2e/rag_test.go, website/docs/usage.md, website/versioned_docs/version-v0.5.x/usage.md, website/versioned_docs/version-v0.6.x/usage.md
Ensures consistency when using `KAITO` acronym across documentation and comments.
- Updated proposals
Fixes #1397
=> docs: Fix KAITO acronym alignment

website/docs/model-as-oci-artifacts.md
=> docs: fix typo in model-as-oci-artifacts.md

docs/proposals/20250820-byo-nodes.md, docs/proposals/20250902-cloud-provider-agnostic-scheduling.md
=> docs: Add proposal for using NVIDIA GPU feature discovery to support generic cloud provider nodes
