.github/workflows/kaito-e2e.yaml

Ensure e2e install az cli before login.

fix: install cli in e2e-test

---

cmd/models.go
pkg/inference/interface.go
pkg/inference/preset-inference-types.go
pkg/utils/plugin/plugin.go
presets/llama2chat/model.go

This is the first PR of a series of refactoring changes for moving all model specific configurations into preset directory so that the core controllers will be model agnostic. 
- This change introduces Kaito model plugin.
- This change adds the common model interface.
- This change adds corresponding inference implementation for llama-2-chat model family. 
NOTE: the added code is not activated (used) in the controller yet.

chore: Refactor to implement model plugin - part 1

---

cmd/models.go
presets/falcon/model.go
presets/llama2/inference-api.py
presets/llama2/model.go
presets/llama2chat/inference-api.py

This change main does:
1) Add plugin files for llama2 and falcon.
2) Copy the inference.py to the new folders.

chore: Refactor to implement model plugin - part 2

---

Makefile
docker/kaito/Dockerfile
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/inference/interface.go
pkg/inference/preset-inferences.go
pkg/inference/preset-inferences_test.go
pkg/machine/machine_test.go
pkg/resources/manifests_test.go
pkg/utils/plugin/plugin.go
pkg/utils/testUtils.go
presets/models/falcon/model.go
presets/models/llama2/model.go
presets/models/llama2chat/model.go
test/e2e/preset_test.go

This change activates all model plugins. 
- Remove all hard coded model name in workspace_controller.go by using the plugin modelregister.
- Fix related UTs 
- Change the model interface for better abstraction
- Change to use Deployment for llama2-7b models.

chore: Refactor to implement model plugin - part 3

---

.github/workflows/tests.yml
docs/proposals/YYYYMMDD-model-template.md

This PR adds a template to guide Kaito users to propose for adding new models.

docs: add new model proposal template

---

.github/workflows/e2e-preset-configs.json
.github/workflows/e2e-preset-test.yml
.github/workflows/preset-image-build.yml

In this PR we:
1. Place e2e configuration params in a separate JSON
2. Switch from using a hardcoded env variable for image tag version -> Using support-models.yaml tag as source of truth
3. Prevent empty matrix error during build preset pipeline
4. Test/Prod Image Handling Scenarios (See Below)
Discussion: 
This PR addresses three scenarios for image handling:
1. Absent in Test ACR: Logs an error and skips E2E.
2. Present in Test but Absent in Prod ACR: Executes E2E tests (and upon manual trigger and successful E2E, imports the image to Prod)
3. Present in Both Test and Prod ACRs: Currently, E2E tests run without importing.
For the third scenario, to streamline our process and enforce tagging discipline, we could skip E2E tests for images already in Prod, only logging a notice. Thoughts? …

feat: Part 3 - Update E2E tests for new Build Preset Pipeline

---

.github/workflows/e2e-preset-test.yml
pkg/inference/preset-inferences.go
pkg/model/interface.go
presets/models/falcon/model.go
presets/models/llama2/model.go
presets/models/llama2chat/model.go

This PR adds image tag into models.go, so that we can control what preset image Kaito controller is using (establishes controllable link between kaito and preset). 
PR also adds minor fix to e2e-preset-tests ensuring image tag is bumped.

feat: Part 4 - Add image tag to models

---

.github/workflows/e2e-preset-test.yml
.github/workflows/preset-image-build.yml

ci: Part 4.5 - Fix Minor Bugs in E2E Preset Pipeline

---

README.md
docs/How-to-add-new-models.md
docs/proposals/YYYYMMDD-model-template.md

This PR adds a doc to describe the entire workflow of adding a new model to Kaito supported list.

docs: Add instructions about how to add new model in kaito

---

.github/workflows/e2e-preset-test.yml
.github/workflows/kind-cluster/main.py
.github/workflows/preset-image-build.yml

Currently E2E Preset pipeline is relying off the supported_models.yaml, it needs to use the same determine models script that build pipeline is using - to figure out what is needed for testing. 
Additionally this PR adds debug logs for K8s jobs during the build process.

fix: Part 5.5 - Add determine models code to e2e

---

.github/workflows/preset-image-build.yml

When an image of a given tag already exists in ACR, no need to clog pipeline for rebuilding. Pass the build and move on to images that need rebuilding, this will save lots of time.

feat: Prevent unnecessary build re-triggers

---

.github/e2e-preset-configs.json
.github/workflows/e2e-preset-test.yml
.github/workflows/kaito-e2e.yaml
.github/workflows/kind-cluster/determine_models.py
test/e2e/preset_test.go
test/e2e/utils/utils.go

Switch off of existing AMR ACR for Production one
PR also introduces a boolean "Run all e2e tests" which if checked will run e2e on all models, overriding whether supported_models.yaml was updated. This was necessary for importing models into the new prod ACR.

fix: Switch to Production ACR

---

presets/models/llama2/model.go
presets/models/llama2chat/model.go

Given llama is private preset, llama Tag in models.go wasn't being used

fix: Remove Llama Tag

---

Makefile
test/e2e/e2e_test.go

Add make target to help running e2e locally:
```shell
AZURE_LOCATION=westus2 make create-rg
AZURE_LOCATION=westus2 make create-aks-cluster-with-kaito
AZURE_SUBSCRIPTION_ID=<SUB_ID> AZURE_LOCATION=westus2 make prepare-kaito-addon-identity
az aks update --resource-group demo --name kaito-demo --attach-acr /subscriptions/<>/resourceGroups/<>/providers/Microsoft.ContainerRegistry/registries/<> 
kubectl create secret docker-registry aimodelsregistrysecret \                                                      
--docker-server=<> \
--docker-username=<> \
--docker-password=<>
AI_MODELS_REGISTRY=<> AI_MODELS_IMAGE_VERSION=0.0.1 RUN_LLAMA_13B=false \
AI_MODELS_REGISTRY_SECRET=<> GPU_NAMESPACE=kube-system KAITO_NAMESPACE=kube-system \
make kaito-workspace-e2e-test
````

feat: Add make target to run e2e local

---

presets/README.md

feat: Update README.md

---

Makefile

I'm assuming this should be `.PHONY` not `.PHONE`

fix: Fix typo in Makefile

---

Makefile
charts/kaito/gpu-provisioner/README.md
charts/kaito/gpu-provisioner/templates/clusterrole-core.yaml
charts/kaito/gpu-provisioner/templates/configmap-logging.yaml
charts/kaito/gpu-provisioner/templates/configmap.yaml
charts/kaito/gpu-provisioner/templates/deployment.yaml
charts/kaito/gpu-provisioner/templates/role.yaml
charts/kaito/gpu-provisioner/templates/rolebinding.yaml
charts/kaito/gpu-provisioner/templates/serviceaccount.yaml
charts/kaito/gpu-provisioner/values.yaml
charts/kaito/workspace/README.md
charts/kaito/workspace/templates/deployment.yaml
charts/kaito/workspace/templates/nvidia-device-plugin-ds.yaml
charts/kaito/workspace/templates/role.yaml
charts/kaito/workspace/templates/role_binding.yaml
charts/kaito/workspace/templates/secret-webhook-cert.yaml
charts/kaito/workspace/templates/service.yaml
charts/kaito/workspace/templates/serviceaccount.yaml
docs/installation.md

Update helm chart to use `Release.Namespace` instead of chart name.

fix: Update helm chart to use Release.Namespace

---

.github/workflows/publish-gh-image.yml

Remove PR trigger from release workflow. As we follow a branch based approach.

ci: Remove PR trigger from release workflow

---

.github/workflows/publish-gh-image.yml

- The job output for registry was missing.
- calling the output should use the job name, not step one.
- 

fix: Add registry as a pipeline job output

---

presets/inference/text-generation/api_spec.json
presets/inference/text-generation/inference_api.py
presets/inference/text-generation/requirements.txt
presets/inference/text-generation/tests/test_inference_api.py

This change adds plenty more documentation and OpenAPI spec for our inference. It also enables the use of preferred non-NVIDIA nodes without crashing.
Fixes #321 

feat: Add API Docs and Improve Inference Readability

---

pkg/inference/preset-inferences.go
pkg/utils/common-preset.go

Refactoring out reusable logic - in preparation to also be used by tuning preset

chore: Factoring out reusable presets logic - Part 4

---

charts/kaito/workspace/templates/clusterrole_binding.yaml
charts/kaito/workspace/templates/nvidia-device-plugin-ds.yaml
charts/kaito/workspace/templates/role_binding.yaml
charts/kaito/workspace/templates/webhooks.yaml

- Update the namespace to use the release namespace.
Fixes #336 

fix: Update namespace in the helm chart

---

cmd/main.go
pkg/k8sclient/client.go

Add global client, accessible via webhooks
In this PR I also
Separate setup and execution phase of webhook server, allows us to handle setup errors and setup context before attempting to run the webhook server

feat: Add global client, accessible via webhooks

---

pkg/inference/preset-inferences.go
pkg/utils/common-preset.go
pkg/utils/common.go

Add util function for configmapmount and getting release namespace.

feat: Add few util functions

---

api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
charts/kaito/workspace/templates/clusterrole.yaml
pkg/resources/resources.go
pkg/tuning/preset-tuning.go

This PR introduces some of the util functions that are to be used by the function
func CreatePresetTuning(ctx context.Context, workspaceObj *kaitov1alpha1.Workspace,
tuningObj *model.PresetParam, kubeClient client.Client) (client.Object, error)
This function will be in charge of handling launching the training job using the dataset source and uploading results to dataset destination. It is also incharge of ensuring configmap tuning parameters are in the right namespace so they are ready to be used by the fine_tuning_api.py file.

feat: Setup Preset Tuning Util Functions and miscellaneous validation/logging - Part 7

---

pkg/tuning/preset-tuning.go
pkg/tuning/preset-tuning_test.go
pkg/utils/common-preset.go

feat: Add URL as data source

---

.github/workflows/e2e-workflow.yml
Makefile
api/v1alpha1/workspace_validation_test.go
charts/kaito/workspace/templates/deployment.yaml
charts/kaito/workspace/values.yaml
cmd/main.go
cmd/main_test.go
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_gc_finalizer.go
pkg/featuregates/featuregates.go
pkg/featuregates/featuregates_test.go
pkg/tuning/preset-tuning_test.go
pkg/utils/common.go
pkg/utils/consts/consts.go

- Add `feature-gates` flag to the Kaito controller.
- Support the `karpenter` feature gate with default value, `false`. 
- Enable setting the feature gate flag via helm chart.
In addition to some chores:
- Exclude the auto generated and mock files from unit test coverage.
- Upgrade k8s version using in the tests to the current supported version.

feat: Add feature gates flag

---

api/v1alpha1/workspace_condition_types.go
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/controllers/workspace_gc_finalizer.go
pkg/controllers/workspace_gc_finalizer_test.go
pkg/controllers/workspace_status.go
pkg/machine/machine.go
pkg/machine/machine_test.go
pkg/nodeclaim/nodeclaim.go
pkg/resources/manifests.go
pkg/resources/nodes.go
pkg/utils/consts/consts.go
pkg/utils/test/testUtils.go

- Workspace controller can support `nodeClaims` API.
Workspace controller won't migrate the current `machine` nodes. The behavior for CRUD operation:
**Create**
- Both `nodeClaims` or `Machine` APIs will be used to create a node based on featureGate,
**Ownership**
- Both `machines` and `nodeClaims` objects which created by the same workspace will be associated to it until got deleted. 
**Delete**
- Deleting the workspace will delete both (if any) old `machines` objects and `nodeClaims`.
- Add unit tests for supporting node claims, and managing migrated clusters (both machines and nodeClaims).
- Replace the deprecated func `FromInt` with `FromInt32`.
- Update error message lint warning, start with lowercase characters.
#339 
**Notes …

feat: Support Karpenter NodeClaim API in workspace

---

charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
config/crd/bases/kaito.sh_workspaces.yaml

We recently upgraded the controller-gen to a recent version. The generated CRD should be updated with the new controller-gen tool.

chore: update crd generated by 0.15 controller-gen

---

pkg/tuning/preset-tuning.go
pkg/tuning/preset-tuning_test.go

Minor bugfix for filepath for results dir

fix: Tuning Results Filepath Bugfix

---

api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
examples/inference/kaito_workspace_falcon_7b.yaml
examples/inference/kaito_workspace_falcon_7b_with_adapters.yaml
pkg/inference/preset-inferences.go
pkg/resources/manifests.go
pkg/utils/common-preset.go
presets/inference/text-generation/inference_api.py
presets/inference/text-generation/requirements.txt
presets/test/manifests/falcon-7b-with-adapter/falcon-7b.yaml

feat: Automate the adapters manifests

---

docker/presets/models/llama-2/Dockerfile
presets/models/llama2/README.md
presets/models/llama2chat/README.md

Update instructions for building llama2 container images.
N/A
Verified container images run after consolidating llama2 model weight files into a single directory. Also fixed path error in llama2 Dockerfile when running build from root of the repo.

docs: update instructions for llama2

---

api/v1alpha1/workspace_validation_test.go
pkg/inference/preset-inferences_test.go

chore: increase adapter test coverage

---

pkg/controllers/workspace_controller.go
pkg/inference/preset-inferences.go
pkg/tuning/preset-tuning.go
pkg/tuning/preset-tuning_test.go
presets/inference/text-generation/requirements.txt
presets/tuning/text-generation/requirements.txt
test/e2e/preset_test.go
test/e2e/utils/utils.go
test/e2e/webhook_test.go

Renaming functions, updating configs and services

feat: Add Util funcs, updating func names, logs, configs and ensure service requirement

---

test/e2e/utils/utils.go
test/e2e/webhook_test.go

chore: tuning e2e webhook test

---

.github/workflows/e2e-workflow.yml
Makefile
docker/adapter/Dockerfile
docker/adapter/README.md
docker/adapter/adapter_config.json
presets/inference/text-generation/inference_api.py
test/e2e/inference_with_adapters.go
test/e2e/preset_test.go
test/e2e/utils/utils.go
test/e2e/webhook_test.go

chore: e2e test for adapters and validation of adapters

---

.github/actions/build-image-action/action.yml
.github/workflows/kind-cluster/main.py

Preset images use their model name as the name of the image by default. Instead we pass in seperate image name variable to name the image.

fix: Preset Build Image Naming

---

.github/workflows/create-release.yml

The gorelaser release following subcommands has been changed:
- `--rm-dist` [deprecated](https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md#--rm-dist) and replaced by `--clean`
- `--debug` [deprecated](https://github.com/goreleaser/goreleaser/blob/main/www/docs/deprecations.md#--debug) and replaced by `--verbose`

chore: remove deprecated goreleaser release actions

---

docker/kaito/Dockerfile

Due to the new Docker policy, the dockerfile needs to be updated to use the golang and distroless mcr images.

chore: Update docker base images with mcr

---

.github/workflows/publish-gh-image.yml
.github/workflows/publish-mcr-image.yml
Makefile
charts/kaito/workspace/README.md
go.sum
goreleaser.yml

- Replace `multiarch/qemu-user-static` with `mcr.microsoft.com/mirror/docker/multiarch/qemu-user-static:7.2.0-1`

fix: Update qemu image

---

pkg/sku/cloud_sku_handler.go
pkg/utils/common.go
pkg/utils/consts/consts.go

- Reading the CLOUD_PROVIDER environment variable and initializing the respective SKUHandler to access the correct list of gpu skus
This PR does not change anything in the current implementation to keep things clean. The next PR will get rid of sku_config from v1alpha1 and carry out necessary refactoring and test updates.

feat: [SKU-modularization] Get SKU Handler

---

charts/kaito/workspace/templates/lora-params.yaml
charts/kaito/workspace/templates/qlora-params.yaml

This PR removes the extra newline/space char (probably from a different encoding) from the yaml. This extra char causes display issue as the whole config file is converted to string with "\n" to represent newline. The resultant configmap is not readable.
Before the change, 
```
k get configmap/lora-params-template -n workspace -o yaml
apiVersion: v1
data:
training_config.yaml: "training_config:\n  ModelConfig: # Configurable Parameters:
https://huggingface.co/docs/transformers/v4.40.2/en/model_doc/auto#transformers.AutoModelForCausalLM.from_pretrained\n
\   torch_dtype: \"bfloat16\"\n    local_files_only: true\n    device_map: \"auto\"\n\n
\ QuantizationConfig: # Configurable Parameters: https://huggingface.co/docs/transformers/v4.40.2/en/main_classes/quantization#transformers.BitsAndBytes …
```

fix: remove extra char from configmap

---

pkg/controllers/workspace_controller.go

This PR addresses two problems:
1) We should add watcher for tunning jobs. Otherwise, if a tunning job is deleted before it is done, the controller will not recreate it. 
2) Currently, the gpu-provisioner will update the machine object with heartbeat information every two minutes. This will trigger a workspace reconcile. In practice, if the machine keeps in the ready state, we don't need to reconcile the workspace. Add an additional machine event filter to avoid unnecessary reconciles.

fix: add watcher for job and avoid unnecessary reconcile

---

examples/fine-tuning/kaito_workspace_tuning_phi_3.yaml
presets/tuning/text-generation/fine_tuning.py

Use callback function to clear CUDA cache to reduce OOM every training step.

fix: Clear CUDA cache to reduce OOM

---

pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/resources/manifests.go
pkg/utils/test/testUtils.go

1. Update deployment object when adapter changes are detected
2. Include logic for comparing adapters 
3. Add unit test for deployment update

feat: Update deployment object when adapter changes are detected

---

.github/workflows/e2e-workflow.yml
Makefile
docker/dataset/Dockerfile
docker/dataset/README.md
test/e2e/inference_with_adapters.go
test/e2e/preset_test.go
test/e2e/utils/utils.go

This PR ensures we use an image for dataset that is locally built during e2e as opposed to an external URL. 
This prevents flakey network errors that can waste entire pipeline runs.
Addresses - https://github.com/Azure/kaito/issues/531

feat: Add Dataset Image Use for E2E Tests

---

pkg/controllers/workspace_controller.go
pkg/resources/manifests.go

add volumeMounts and volume patch for initContainers
add nil check for annotations

chore: patch for volumeMounts

---

README.md

Fixes quick start tutorial's path for inference in the main readme. 

fix: falcon config path in quick start

---

.github/workflows/helm-chart.yml

To be able to run helm chart publish workflows on demand. I noticed the latest version (0.3.0) of the helm chart is not published to https://azure.github.io/kaito/charts/kaito and looks like this can be resolved by simply re-running the publish workflow (without creating a new release). 
Confirmed this works in my fork of the kaito repo. Re-running the workflow published new chart version 0.3.0 (with app version 0.3.0)
Verify helm chart and app versions
```
helm repo add kaito https://azure.github.io/kaito/charts/kaito
helm search repo --versions kaito/workspace
helm search repo --versions kaito/gpu-provisioner
```

ci: adding workflow dispatch to helm-chart workflow

---

.github/workflows/e2e-workflow.yml
api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
pkg/controllers/workspace_controller.go
pkg/tuning/preset-tuning.go
pkg/utils/common-preset.go
pkg/utils/common.go
test/e2e/preset_test.go

- Keep the docker sidecar container alive so incase ACR push fails we can still exec into the container to retrieve completed tuning job files in the /mnt/results folder.
- Perform validation check for output images that are uppercase
- Use projected volume for mounting docker config secrets - mount at directory location /root/.docker/config
- Add secret for E2E Temp ACR

fix: Keep Docker Sidecar Alive for Data Retrieval

---

.github/e2e-preset-configs.json
.github/workflows/e2e-preset-test.yml
presets/test/manifests/falcon-7b-adapter/falcon-7b-adapter-service.yaml
presets/test/manifests/falcon-7b-adapter/falcon-7b-adapter.yaml

This PR adds a test for loading a mental health adapter onto the falcon-7b model. And testing to make sure the adapter was loaded onto the model successfully using `inference_api.py` logs.

feat: Add Adapter Loading Test for E2E Image Preset Workflow

---

.github/workflows/kaito-e2e.yml
Makefile
hack/deploy/generate-identities.sh
test/e2e/e2e_test.go
test/e2e/inference_with_adapters_test.go
test/e2e/preset_test.go
test/e2e/utils/cluster.go
test/e2e/utils/machine.go
test/e2e/utils/nodeclaim.go
test/e2e/webhook_test.go

- Add Karpenter e2e tests 
- Add support for Azure Karpenter in the e2e workflow.
- Organize e2e code base
- 

test: Add e2e tests for azure karpenter

---

api/v1alpha1/workspace_labels.go
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/inference/preset-inferences.go
pkg/inference/preset-inferences_test.go
pkg/resources/manifests.go
pkg/resources/manifests_test.go
pkg/utils/test/testUtils.go

1. Change "workspace.kaito.io/revision" to revision number, and make the hash result as "workspace.kaito.io/hash"
2. Sync contropllerrevision and workspace at the beginning of the Reconcile
3. Update the tests for the changes

feat: Update controllerRevision and deployment lifecycle 

---

test/e2e/inference_with_adapters_test.go
test/e2e/utils/utils.go

Add adapters validation to e2e tests.

chore: adapter validation e2e

---

pkg/resources/resources.go
pkg/resources/resources_test.go

1. Add error checking to CheckResourceStatus:
- For tuning job, when fail pods detected, change status and don't need to wait till time limit.
-  For inference job, when DeploymentProgressing is failed, change status and don't need to wait till time limit.
2. Add unit test

feat: Add error checking to CheckResourceStatus

---

Makefile
api/v1alpha1/ragengine_types.go
charts/kaito/ragengine/crds/kaito.sh_ragengines.yaml
config/crd/bases/kaito.sh_ragengines.yaml

add WorkerNodes to RAGEngineStatus

feat: add WorkerNodes to RAGEngineStatus

---

.github/workflows/e2e-workflow.yml
api/v1alpha1/workspace_types.go
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/utils/test/testUtils.go

ignore instanceType when selecting preferred nodes

fix: ignore instanceType when selecting preferred nodes

---

pkg/controllers/ragengine_status.go
pkg/controllers/ragengine_status_test.go
pkg/controllers/workspace_status.go
pkg/controllers/workspace_status_test.go

refactor updateObjStatus for both RAG and workspace

feat: refactor updateObjStatus for both RAG and workspace

---

ragengine/embedding/base.py
ragengine/embedding/huggingface_local.py
ragengine/embedding/huggingface_remote.py
ragengine/requirements.txt

This series of PR will integrate llamaindex RAG service for Kaito. 
This first PR introduces the Embedding Model Interface and two classes that implement it `huggingface_local` and `huggingface_remote`. These allows users to specify both local and remote HuggingFace models for text embeddings.

feat: Part 1 - Add RAG Embedding Interface

---

ragengine/config.py
ragengine/inference/custom_inference.py
ragengine/inference/inference.py

This series of PR will integrate llamaindex RAG service for Kaito.
This PR contains the custom LLM inference class for llamaindex. We need this class because we use custom HTTP endpoint or OpenAI API for handling LLM requests so we need a custom LLM inference class.
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom/#example-using-a-custom-llm-model-advanced

feat: Part 2 - Add custom LLM inference class

---

README.md
terraform/.gitignore
terraform/README.md
terraform/gpu-provisioner-values.tmpl
terraform/kaito.tf
terraform/kubernetes.tf
terraform/locals.tf
terraform/main.tf
terraform/outputs.tf
terraform/registry.tf
terraform/variables.tf

Provision AKS cluster and deploy KAITO using Terraform
See ./terraform/README.md for more information on how to deploy

docs: quick deploy using terraform

---

terraform/.terraform.lock.hcl
terraform/README.md
terraform/kaito.tf

Fixes a bug found in Terraform configuration which was not properly storing ACR token as a K8s dockerconfigjson secret. Also updating the README to point users to examples and docs after provisioning resources and installing KAITO.

docs: fix terraform and update readme

---

.github/workflows/e2e-workflow.yml
.github/workflows/kaito-e2e.yml

To remove dependency on GitHub secrets and environments (which are only accessible by maintainers). Use Self-Hosted runner.

feat: Migrate E2E pipeline to using Self-Hosted Runner

---

pkg/controllers/workspace_controller.go
pkg/inference/preset-inferences.go
pkg/inference/preset-inferences_test.go
test/e2e/inference_with_adapters_test.go

fix the bug that adapter with ImagePullSecrets will not be populated to its deployment

fix: Populate ImagePullSecrets in Adapter Deployment and Add Corresponding Tests

---

Makefile
test/e2e/inference_with_adapters_test.go

patch imagePullSecrets validation in e2e test, only the second image need this check

fix: patch imagePullSecrets validation in e2e test

---

cmd/ragengine/main.go
cmd/workspace/main.go
pkg/ragengine/webhooks/webhooks.go
pkg/workspace/webhooks/webhooks.go

Split webhook.go for workspace and ragengine controller individually.

chore: restruct workspace controller code - part 4

---

api/v1alpha1/condition_types.go
charts/kaito/ragengine/templates/deployment.yaml
charts/kaito/ragengine/values.yaml
pkg/ragengine/controllers/preset-rag.go
pkg/ragengine/controllers/preset-rag_test.go
pkg/ragengine/controllers/ragengine_controller.go
pkg/ragengine/manifests/manifests.go
pkg/ragengine/manifests/manifests_test.go
pkg/utils/test/testUtils.go

Generate and create RAGengine deployment - part 1 

feat: RAG engine deployment creation

---

.github/workflows/e2e-workflow.yml
Makefile
api/v1alpha1/workspace_types.go
charts/kaito/workspace/Chart.yaml
charts/kaito/workspace/README.md
charts/kaito/workspace/values.yaml
docs/installation.md
examples/inference/kaito_workspace_phi_3_medium_128k.yaml
examples/inference/kaito_workspace_phi_3_medium_4k.yaml
examples/inference/kaito_workspace_phi_3_mini_128k.yaml
examples/inference/kaito_workspace_phi_3_mini_4k.yaml
pkg/controllers/workspace_controller.go
pkg/controllers/workspace_controller_test.go
pkg/utils/test/testUtils.go
presets/models/phi2/README.md
presets/models/phi3/README.md

release: Update manifest and helm charts for v0.3.2

---

.github/workflows/publish-mcr-image.yml

it runs e2e test once on the ghcr pipeline, there is no point to run e2e again.

fix: skip e2e test for mcr publish pipeline

---

Makefile
README.md
charts/kaito/workspace/Chart.yaml
charts/kaito/workspace/README.md
charts/kaito/workspace/values.yaml
docs/installation.md
terraform/variables.tf

Change the main branch to reflect the latest release.

docs: update docs with 0.3.2 release

---

docs/installation.md

I discussed an issue that the default installation of Kaito failed to work as it could create the GPU provisioner in a default name space and customers need to manually change the namespace to "default" to ensure the GPU provisioner pod is in running status
Fix the document for the helm install command. The command is validated in the latest AKS cluster and discussed with Fei.

Avoid creating GPU provisioner in the default namespace

---

docs/installation.md

Fix to onboarding documentation. New users might be surprised to find no helm deployments when in fact they were pushed correctly.
None
Fix after https://github.com/kaito-project/kaito/pull/706.

docs: Update helm list command in installation guide to use new namespaces.

---

docs/kaito-on-BYO-gpu-nodes.md

This commit adds a guide for running Kaito on BYO GPU nodes over the default mechanism of using the gpu provisioner.
Some times users may not have permission to assign roles in their subscription. Since it is needed when using the gpu provisioner controller, as documented here: https://github.com/kaito-project/kaito/blob/main/docs/installation.md#create-an-identity-and-assign-permissions. But users may still have permissions to deploy GPU nodes in their clusters. This guide will help folks who can deploy GPU nodes manually to still use Kaito.

docs: Add guide for running Kaito on BYO GPU nodes

---

.github/workflows/preset-image-build.yml
docker/presets/models/tfs/Dockerfile
presets/workspace/dependencies/requirements.txt
presets/workspace/inference/text-generation/inference_api.py
presets/workspace/tuning/text-generation/cli.py
presets/workspace/tuning/text-generation/fine_tuning.py
presets/workspace/tuning/text-generation/parser.py

feat: bump accelerate to 1.0.0

feat: bump accelerate to 1.0.0

---

Makefile
api/v1alpha1/labels.go
api/v1alpha1/workspace_validation.go
pkg/featuregates/featuregates.go
pkg/model/interface.go
pkg/utils/common-preset.go
pkg/utils/common.go
pkg/utils/common_test.go
pkg/utils/consts/consts.go
pkg/utils/plugin/plugin.go
pkg/utils/test/testModel.go
pkg/utils/test/testUtils.go
pkg/workspace/controllers/workspace_controller.go
pkg/workspace/inference/preset-inference-types.go
pkg/workspace/inference/preset-inferences.go
pkg/workspace/inference/preset-inferences_test.go
pkg/workspace/tuning/preset-tuning.go
pkg/workspace/tuning/preset-tuning_test.go
presets/workspace/models/falcon/model.go
presets/workspace/models/llama2/model.go
presets/workspace/models/llama2chat/model.go
presets/workspace/models/mistral/model.go
presets/workspace/models/phi2/model.go
presets/workspace/models/phi3/model.go
test/e2e/preset_vllm_test.go
test/e2e/utils/utils.go

- support vllm runtime deployments
- add a feature gate to enable vllm runtime
- able to select runtime by annotation tag

feat: support vllm in controller

---

presets/ragengine/inference/inference.py

Remote HuggingFace API uses a particular format: 
```
curl 'https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta/v1/chat/completions' \
-H 'Authorization: Bearer hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
-H 'Content-Type: application/json' \
--data '{
"model": "HuggingFaceH4/zephyr-7b-beta",
"messages": [
{
"role": "user",
"content": "What is the capital of France?"
}
],
"max_tokens": 500,
"stream": false
}'
```
This needs to be adhered to in the code. 
Reference: https://huggingface.co/HuggingFaceH4/zephyr-7b-beta?inference_api=true
Adding this code ensures we continue to support OAI, HF Remote and Custom URL as our LLM backend

feat: Handle HF Remote API Call Format

---

docs/custom-model-integration/custom-deployment-template.yaml

Fix the `inference_api.py` filepath used in custom-deployment-template.yaml
https://github.com/kaito-project/kaito/issues/753

fix: Filepath in custom-deployment-template.yaml

---

charts/kaito/ragengine/README.md

Notify users that kaito ragengine is still WIP, not ready for deployment.

chore: Mark ragengine as WIP for helm installation

---

.github/workflows/publish-rag-service-image.yml
Makefile

This pipeline is responsible for building the RAG Service and then pushing it to `ghcr`. Since RAG Service image is more manageable we can use `ghcr` to manage it.

feat: Add build pipeline for RAG Service

---

pkg/ragengine/controllers/ragengine_controller.go
pkg/ragengine/controllers/ragengine_gc_finalizer.go
pkg/workspace/controllers/workspace_controller.go
pkg/workspace/controllers/workspace_gc_finalizer.go

We need to select Machine or NodeClaim to connect gpu-provisioner component to provide GPU resource.
this means Machine and NodeClaim can not supported at the same time.
In this pull request, improve some sequence process of Machine and NodeClaim into `if condition`.

fix: machine and nodeclaim can not supported at the same time

---

presets/workspace/inference/chat_templates/chat_template_guide.md

**Requirements**:
- Starting from transformers version 4.42, a chat template must be provided for chatting service. It's a low-level configuration file in jinja format that defines the constraints for [chat message](https://platform.openai.com/docs/api-reference/chat) input. 
- [Hugging Face reference](https://huggingface.co/docs/transformers/v4.43.4/en/chat_templating#templates-for-chat-models) -
- This PR explains these rules to end users in a simplified natural language.
Fixes: #661 
- This is my very first contribution to the Kaito project 🤗. Please let me know your thoughts on this documentation and how we can further streamline it for Kaito end users.
- CC: @zhuangqh @sdesai345

docs: add LLMs chat template documentation for end-users

---

README.md

Adding an  invite link for Kaito community slack channel in project README.
Slack channel is originally created by @sdesai345

docs: Add invite link to the Kaito community slack

---

docker/presets/models/llama-2/Dockerfile

This updates the Python version to 3.9-slim in the Dockerfile for the Llama 2 model, so that the new features specific to Python 3.9 can be used by the inference_api.py.
Fixes #797

llama2-Dockerfile: Update Python to 3.9-slim

---

.github/workflows/helm-chart.yml
.github/workflows/publish-workspace-mcr-image.yml

As part of tighten the security for Kaito pipelines, we enforced approval-based for all workflows that perform writing to the repo. One of the side effects of this was a required approval for the auto triggered 'pages build and deployment' workflow which was missing - and it will get canceled when creating a new release - and caused the helm github page repo to not get updated (#808).
As a solution to that, we will change the Make publish helm chart and create release workflows to run sequentially instead of parallel, so new release won't get created until all (including github pages) are updated successfully.

ci: Make publish helm chart and create release workflows sequential

---

.github/workflows/unit-tests-ragengine.yml
.github/workflows/unit-tests.yml
Makefile

Add RAG and other Python code UT coverage to the codecov report to ensure that the RAG server changes for consistency are tested and the code coverage is reported accurately.

test: Add RAG and other Python UT coverage to the codecov report

---

README.md
docs/custom-model-integration/custom-deployment-template.yaml
docs/custom-model-integration/reference-image-deployment.yaml
docs/inference/README.md
examples/inference/kaito_workspace_falcon_7b-instruct.yaml
examples/inference/kaito_workspace_falcon_7b.yaml
examples/inference/kaito_workspace_falcon_7b_with_adapters.yaml
examples/inference/kaito_workspace_llama2_13b-chat.yaml
examples/inference/kaito_workspace_llama2_13b.yaml
examples/inference/kaito_workspace_llama2_7b-chat.yaml
examples/inference/kaito_workspace_llama2_7b.yaml
examples/inference/kaito_workspace_mistral_7b-instruct.yaml
examples/inference/kaito_workspace_mistral_7b.yaml
examples/inference/kaito_workspace_phi_2.yaml
examples/inference/kaito_workspace_phi_3.5-instruct.yaml
examples/inference/kaito_workspace_phi_3_mini_128k.yaml
examples/inference/kaito_workspace_phi_3_mini_4k.yaml
examples/inference/kaito_workspace_phi_3_with_adapters.yaml

v3 GPU SKUs have been deprecated by Azure. Hence, using v4 GPU as a default SKU in the documentation.

docs: Update to use Standard_NC24ads_A100_v4 as default SKU in docs

---

cmd/workspace/models.go
presets/workspace/models/deepseek/model.go

feat: Add DeepSeek Model Plugin

---

pkg/workspace/inference/preset-inference-types.go
presets/workspace/models/deepseek/model.go
presets/workspace/models/falcon/model.go
presets/workspace/models/mistral/model.go
presets/workspace/models/phi2/model.go
presets/workspace/models/phi3/model.go
presets/workspace/models/qwen/model.go

fix: DeepSeek Model Naming

---

terraform/variables.tf

Bumping gpu-provisioner version to latest 0.3.1

chore: bump gpu-provisioner in terraform sample

---

.github/workflows/codeql.yml
.github/workflows/create-release.yml
.github/workflows/dependency-review.yml
.github/workflows/e2e-base-setup.yaml
.github/workflows/helm-chart.yml
.github/workflows/lint-go.yml
.github/workflows/markdown-link-check.yml
.github/workflows/pr-title-lint.yml
.github/workflows/publish-rag-controller-gh-image.yml
.github/workflows/publish-rag-service-gh-image.yml
.github/workflows/publish-workspace-gh-image.yml
.github/workflows/unit-tests-ragengine.yml
.github/workflows/unit-tests.yml

This PR updates workflows in the this repository to enable the following security configurations by default:  
- **`disable-sudo: true`** → Prevents unnecessary privilege escalations.  
- **`disable-telemetry: true`** → Disables telemetry to enhance privacy.  
These settings provide a **baseline security enhancement**, but users can **opt to enable full-level access** based on their workflow needs and understanding.  
These flags serve as a good starting point.  
📌 **References:**  
- [Disable Telemetry](https://docs.stepsecurity.io/harden-runner/how-tos/disable-telemetry/)  
- [Disable Sudo](https://docs.stepsecurity.io/harden-runner/how-tos/disable-sudo/)  
Thank you so much for letting me add this to your repo, please accept if this feels good.

chore: Curb the permissions for publishing data to third party dashboards.

---

presets/ragengine/requirements.txt
presets/ragengine/tests/api/test_main.py
presets/ragengine/vector_store/base.py
presets/ragengine/vector_store/faiss_store.py

This PR introduces an async read–write lock mechanism (using `aiorwlock.RWLock`) to ensure thread safety for concurrent document indexing and querying operations. The RWLock is conditionally enabled for vector store implementations that require concurrent write protection (e.g., Faiss-based stores), while other implementations can continue without it.

feat: Add Async RWLock for Safe Concurrent Index Operations in Select Vector Stores

---

.github/actions/e2e-base-setup/action.yml
.github/workflows/e2e-workflow.yml
.github/workflows/ragengine-e2e-workflow.yml
.github/workflows/ragengine-e2e.yml
pkg/ragengine/controllers/preset-rag.go
pkg/ragengine/controllers/preset-rag_test.go
test/rage2e/rag_test.go

1. Use composite steps for avoiding cleaning step is not run when interrupted.
2. Add RAG pipeline back when rag engine related codes are changed.
3. Use the image aimodelsregistrytest.azurecr.io/kaito-rag-service:0.0.7 for now, will change it back when MCR image is good
4. Changed the image in the unit test too

chore: RAG pipeline leaking cluster patch

---

presets/ragengine/models.py
presets/ragengine/vector_store/base.py

https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/
"Typically, a document might have many metadata keys, but you might not want all of them visible to the LLM during response synthesis."

fix: Excluding Metadata to LLM during Response Synthesis & Updating default top_k

---

presets/ragengine/embedding/base.py
presets/ragengine/embedding/huggingface_local_embedding.py
presets/ragengine/embedding/remote_embedding.py
presets/ragengine/main.py
presets/ragengine/tests/api/test_main.py
presets/ragengine/vector_store/base.py
presets/ragengine/vector_store/faiss_store.py
presets/ragengine/vector_store_manager/manager.py

1. Refactors the embedding model architecture to directly implement llama_index.core.embeddings.BaseEmbedding, ensuring better integration with LlamaIndex and improved flexibility across different embedding backends.
2. Adds the `/load/{index_name}` API endpoint, enabling users to load persisted vector indexes from disk.

feat: Generalize Embedding Model Class & Add /load Endpoint for Index Management

---

presets/ragengine/main.py
presets/ragengine/vector_store/base.py
presets/ragengine/vector_store_manager/manager.py

Add the ability to overwrite existing indexes when loading them.

feat: Add overwrite to load index

---

cmd/workspace/main.go
pkg/featuregates/featuregates.go
pkg/featuregates/featuregates_test.go
pkg/utils/consts/consts.go

Not all node auto provisioner requires the NodeClass CRD. To minimize the dependency, add the feature gate ensureNodeClass to skip auto generate NodeClass unless it is needed. 
The feature is false by default.
#898

feat: add featuregate for ensureNodeClass

---

api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go

Adding Preset name validation in validateCreateWithInference
Fixes #903 

fix: Adding Preset name validation in validateCreateWithInference

---

api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
api/v1beta1/condition_types.go
api/v1beta1/labels.go
api/v1beta1/workspace_validation.go
api/v1beta1/workspace_validation_test.go
charts/kaito/workspace/templates/deployment.yaml
pkg/utils/test/testUtils.go

This change ports the preset name validation fix from v1apha1 to v1beta1 webhook.  This fix is omitted during v1beta1 api promotion process.
The original fix does not completely resolve the problem. The inferenceSpec.validateCreate will also hit panic if preset name is wrong. In this PR, we slightly change the validation logic. The resourceSpec.validateCreate does not report the error and inferenceSpec.validateCreate will fail fast in case the preset name is wrong. 
The reason why resourceSpec.validateCreate does not report the error is because:
1) The err will be caught by the inferenceSpec.validateCreate 100%.
2) The err msg indicates resource.presetName field is wrong, which can be confusing.
The logic changes are backported to v1alpha1 …

feat: port preset name validation to v1beta1 webhook

---

.github/actions/e2e-base-setup/action.yml
.github/workflows/e2e-base-setup.yaml

E2E Pipelines were failing to run because of name collisions in Azure.
Fixes #953
See https://github.com/kaito-project/kaito/actions/runs/14071339635/job/39405996019?pr=950#step:5:650 and https://github.com/kaito-project/kaito/actions/runs/14071339635/job/39406506397?pr=950#step:5:274.

chore: use run id, number, and attempt to create unique azure resource names

---

.github/actions/e2e-base-setup/action.yml
.github/workflows/create-release.yml
.github/workflows/e2e-base-setup.yaml
.github/workflows/e2e-preset-test.yml
.github/workflows/e2e-preset-tuning-test.yml
.github/workflows/e2e-workflow.yml
.github/workflows/kaito-e2e.yml
.github/workflows/lint-go.yml
.github/workflows/preset-image-build-1ES.yml
.github/workflows/preset-image-build.yml
.github/workflows/publish-rag-controller-gh-image.yml
.github/workflows/publish-rag-service-gh-image.yml
.github/workflows/publish-workspace-gh-image.yml
.github/workflows/publish-workspace-mcr-image.yml
.github/workflows/ragengine-e2e-workflow.yml
.github/workflows/ragengine-e2e.yml
.github/workflows/unit-tests-ragengine.yml
.github/workflows/unit-tests.yml
Makefile
Tiltfile
codecov.yml
docker/ragengine/Dockerfile
docker/workspace/Dockerfile
docs/contributing/readme.md
go.mod

Bump golang version to 1.24 in all pipelines and for go.mod

chore: Bump golang version to 1.24

---

pkg/ragengine/controllers/ragengine_controller.go
pkg/utils/nodeclaim/nodeclaim.go
pkg/workspace/controllers/workspace_controller.go

As discussed with @Fei-Guo  @bangqipropel , kaito should skip the nodeclaim status LastPodEventTime change. so I add a nodeclaim predicated for nodeclaim watch.

feat: skip nodeclaim.Status.LastPodEventTime change event

---

.github/workflows/e2e-preset-test.yml
.github/workflows/e2e-preset-tuning-test.yml
docker/presets/models/tfs/Dockerfile
presets/workspace/dependencies/requirements.txt
presets/workspace/models/supported_models.yaml

- Updated vllm dependency version to 0.8.2.
- Added GCC installation for torch.compile support.
- Removed deprecated custom headers when creating aks node pool.
`--aks-custom-headers UseGPUDedicatedVHD=true` this header was deprecated.
> ERROR: (OperationNotAllowed) AKS no longer supports creating node pools using the GPU image.  If you'd like to create gpu-enabled node pools, please use the supported methods in https://learn.microsoft.com/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool.

fix: add dependencies for vllm runtime

---

presets/workspace/inference/vllm/inference_api.py

Through testing we find chunked prefill unsupported on V100 arch. Detect this and set to false.

fix: Pin disable chunked prefill on V100 Arch

---

api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
api/v1beta1/workspace_validation.go
api/v1beta1/workspace_validation_test.go
go.mod
go.sum
pkg/utils/common-preset.go
pkg/workspace/controllers/workspace_controller.go
pkg/workspace/image/README.md
pkg/workspace/image/puller.go
pkg/workspace/image/puller.sh
pkg/workspace/image/puller_test.go
pkg/workspace/image/pusher.go
pkg/workspace/image/pusher.sh
pkg/workspace/image/pusher_test.go
pkg/workspace/image/suite_test.go
pkg/workspace/manifests/manifests.go
pkg/workspace/tuning/preset-tuning.go
pkg/workspace/tuning/preset-tuning_test.go
test/e2e/e2e_test.go
test/e2e/inference_with_adapters_test.go
test/e2e/preset_test.go
test/e2e/utils/utils.go

This patch allows us to get rid of DinD, which currently runs in a privileged container. Skopeo will be used to pull images, mimicking the exact pull behavior of [K8s Image Volumes](https://kubernetes.io/docs/tasks/configure-pod-container/image-volumes/). While ORAS is used to build the image in a way compatible with the implementation of [K8s Image Volumes](https://kubernetes.io/docs/tasks/configure-pod-container/image-volumes/) in `containerd` and `cri-o`.
Fixes #901
After this patch, images produced with newer versions of Kaito won't run on older versions of Kaito. However, images produced by older versions of Kaito will run on newer versions of Kaito. We probably want to make this clear on the release …

feat: reimplement pull and push of images with skopeo and oras

---

api/v1alpha1/labels.go
api/v1alpha1/workspace_validation.go
api/v1alpha1/workspace_validation_test.go
api/v1beta1/labels.go
api/v1beta1/workspace_validation.go
api/v1beta1/workspace_validation_test.go
examples/README.md

Add a workspace annotation to bypass validation checks for the minimum GPU memory required by their workspace.

feat: Add Annotation Bypass GPU Mem check

---

pkg/ragengine/controllers/ragengine_controller.go
pkg/ragengine/controllers/ragengine_gc_finalizer.go
pkg/workspace/controllers/workspace_controller.go
pkg/workspace/controllers/workspace_gc_finalizer.go

Only add finalizer when the object is not in deletion state.
Otherwise the finalizer will be added/remove again and again until it is finally completely deleted. 

fix: only add finalizer when the object is not in deletion state

---

pkg/workspace/controllers/workspace_controller.go

Should not check preset model in sync loop, this can lead to enqueue and reconcile endlessly.
Since there is already [the same check in validation webhook](https://github.com/kaito-project/kaito/blob/main/api/v1beta1/workspace_validation.go#L433-L436), so just delete the code should be fine.
Anyway, it's inappropriate to check the preset model in the sync loop.

fix: should not check preset model in sync loop

---

.github/workflows/kind-cluster/determine_models.py
.github/workflows/kind-cluster/main.py
.github/workflows/license-header.yml
demo/inferenceUI/chainlit_openai.py
demo/inferenceUI/chainlit_transformers.py
docker/presets/models/tfs-onnx/convert_to_onnx.py
presets/ragengine/__init__.py
presets/ragengine/embedding/__init__.py
presets/ragengine/inference/__init__.py
presets/ragengine/tests/__init__.py
presets/ragengine/tests/api/__init__.py
presets/ragengine/tests/vector_store/__init__.py
presets/ragengine/vector_store/__init__.py
presets/ragengine/vector_store_manager/__init__.py
presets/workspace/inference/text-generation/tests/test_inference_api.py
presets/workspace/inference/text-generation/tests/test_model_config.py
presets/workspace/inference/vllm/tests/test_vllm_inference_api.py
presets/workspace/test/scripts/generate_manifests.py

Enhances the `license-header.yml` workflow to check license headers for both Go and Python files, ensuring consistent licensing across the Kaito codebase.

chore: add license header check for Python files

---

api/v1alpha1/workspace_validation.go
api/v1beta1/workspace_validation.go
pkg/model/interface.go
pkg/workspace/tuning/preset-tuning_test.go
presets/workspace/models/deepseek/model.go
presets/workspace/models/falcon/model.go
presets/workspace/models/llama2/model.go
presets/workspace/models/llama2chat/model.go
presets/workspace/models/metadata.go
presets/workspace/models/mistral/model.go
presets/workspace/models/phi2/model.go
presets/workspace/models/phi3/model.go
presets/workspace/models/phi4/model.go
presets/workspace/models/qwen/model.go

Fully integrates supported_models.yaml as the source of truth for model metadata, replacing hardcoded ModelFamilyName and tag maps in model presets.
**Changes:**
- Updated `PresetParam` in `pkg/model/interface.go` to embed `Metadata` struct, removing `ModelFamilyName` and `Tag`.
- Modified model files (e.g., `deepseek`, `falcon`, `llama2`, `mistral`, etc.) to use `metadata.MustGet` for metadata retrieval.
- Added constants for model names and removed tag maps in model files.
- Enhanced `presets/workspace/models/metadata.go` with `MustGet` function and mutex for thread-safe metadata access.
- Updated `api/v1alpha1` and `api/v1beta1` validation logic to use `params` variable for inference parameters.
- Adjusted `preset-tuning_test.go` to reflect `Metadata` embedding …

refactor: remove fields from PresetParam in favor of embedded Metadata

---

presets/ragengine/tests/api/test_main.py
presets/ragengine/tests/vector_store/test_base_store.py
presets/ragengine/vector_store/base.py

LlamaIndex has some internal node id referencing it uses within its document stores that differ from the [document ID's we create documents with](https://github.com/kaito-project/kaito/blob/10af1f42eddbacb9e335b06bebbb4088cad7b629/presets/ragengine/vector_store/base.py#L44C1-L45C1).
This change updates the response ID's from the internal LlamaIndex nodeIds to the document ID's we create for the documents. I chose the `ref_doc_id` because it is what is stored within the vector store on document additions, so when users look into the vector store(cosmos/postgres/etc.) they will see the same doc id as is returned from the ragengine service.
I also found that the id list build on document create calls with new indexes was also returning a random ordered list by calling …

fix: document id's on list document responses are the same as document id's on create document responses

---

cmd/ragengine/main.go
cmd/workspace/main.go

Managed fields are often very large, taking up around 30% memory space of cache resources.
but we don't need them in the controllers, so strip managed fields in order to reduce cache memory.

feat: strip managed fields for controller informer

---

pkg/sku/azure_sku_handler.go

`Standard_ND96amsr_A100_v4` has 8 A100 GPUs with 80GB each, totaling 640GB of GPU memory, not 80GB.

fix: update GPUMemGB for Standard_ND96amsr_A100_v4

---

Makefile
pkg/model/interface.go
pkg/utils/test/testModel.go
pkg/workspace/inference/preset-inference-types.go
pkg/workspace/inference/preset-inferences.go
pkg/workspace/inference/preset-inferences_test.go
pkg/workspace/manifests/manifests.go
pkg/workspace/tuning/preset-tuning.go
pkg/workspace/tuning/preset-tuning_test.go
presets/workspace/models/deepseek/model.go
presets/workspace/models/falcon/model.go
presets/workspace/models/llama3/model.go
presets/workspace/models/mistral/model.go
presets/workspace/models/phi2/model.go
presets/workspace/models/phi3/model.go
presets/workspace/models/phi4/model.go
presets/workspace/models/qwen/model.go

With https://github.com/kaito-project/kaito/blob/main/docs/proposals/20250325-distributed-inference.md, we are planning to discontinue support for distributed inference with torchrun and Transformers. Instead, users can only run multi-node distributed inference with vLLM going forward.
With Llama 2 removed in #1091, there is currently no preset model that relies on torchrun distributed inference, so now is a good time to clean up before implementing the proposal above.
**Changelog**
- **Makefile**:
- Removed `RUN_LLAMA_13B` variable and references, as Llama 2 13B/70B are deprecated.
- Fixed formatting issues in `aws-karpenter-helm` and `aws-patch-install-helm` targets.
- **pkg/model/interface.go**:
- Replaced `TorchRunParams` and `TorchRunRdzvParams` with …

chore: remove torchrun and distributed inference references

---

examples/inference/arc-examples/kaito_workspace_deepseek_r1_distill_llama_8b_with_customized_config.yaml
examples/inference/arc-examples/kaito_workspace_phi_4_mini.yaml
examples/inference/arc-examples/kaito_workspace_qwen_2.5_coder_7b-instruct.yaml
pkg/sku/arc_sku_handker.go

The GPU memory size of SKU NC16 should be 32 not 48

fix: update arc GPUMem to 32 and add more examples for arc

---

docs/proposals/20250325-distributed-inference.md

- Removed mentions of HuggingFace Transformer
- Updated warning when `workspace.resource.count` is larger than the required node count
- Expanded on container probes and added sequential diagrams

docs: expand on container probes in 20250325-distributed-inference.md

---

api/v1beta1/workspace_validation.go
api/v1beta1/workspace_validation_test.go
docker/presets/models/tfs/Dockerfile
pkg/model/interface.go
pkg/utils/common.go
pkg/utils/common_test.go
pkg/utils/test/testModel.go
pkg/workspace/inference/preset-inference-types.go
pkg/workspace/inference/preset-inferences.go
pkg/workspace/inference/preset-inferences_test.go
pkg/workspace/manifests/manifests.go
presets/workspace/dependencies/requirements.txt
presets/workspace/inference/vllm/multi-node-health-check.py
presets/workspace/models/supported_models.yaml

**Reason for Change:**
Enables Kaito to support multi-node distributed inference for large models (e.g., 400B+ parameters) using the vLLM runtime, addressing the gap in deploying models that exceed single-node GPU memory capacity. Adds validation to prevent HuggingFace Transformers from being used for multi-node distributed inference, as it no longer supports this setup.
**Changes:**
- **api/v1beta1/workspace_validation.go**:
- Updated `validateCreateWithInference` to accept `runtime` parameter and validate that HuggingFace Transformers is not used for multi-node distributed inference when model GPU memory exceeds single-node capacity.
- **api/v1beta1/workspace_validation_test.go**:
- Updated `testModelDownload` to support distributed inference and set GPU memory …

feat: support multi-node distributed inference for vLLM

---

presets/ragengine/requirements-test.txt

pytest-asyncio had a 1.0.0 release that broke out UT's. We will pin it for now to unblock ut pipelines.
broken ut's

fix: pin the pytest-asyncio package

---

pkg/ragengine/controllers/ragengine_controller_test.go
pkg/ragengine/controllers/ragengine_gc_finalizer_test.go
pkg/utils/test/testUtils.go

test: improve ut coverage to ragengine
improve ut coverage from 55.4% to 74.3% for ragengine/controllers

test: improve ut coverage to ragengine

---

test/e2e/e2e_test.go
test/e2e/inference_with_adapters_test.go
test/e2e/preset_test.go
test/e2e/preset_vllm_test.go
test/rage2e/e2e_test.go
test/rage2e/rag_test.go

E2E tests needs to pass the gpu-provisioner pod/deployment checks when running on managed mode. To add flexibility  to the e2e framework, a new go test flag `skip-gpu-provisioner-check` is introduced. default value is false which will check for gpu-provisioner. 

test: Exclude gpu-provisioner check in case of running e2e on managed mode

---

charts/kaito/ragengine/templates/deployment.yaml
charts/kaito/ragengine/values.yaml
pkg/ragengine/controllers/preset-rag.go
pkg/ragengine/controllers/preset-rag_test.go

This makes it so the RAGEngine image can be built from env variables. This will allow for E2E tests to pull the correct image as well as easier image bumps in the future.

feat: update rag engine image url to be build from env

---

website/docs/kaito-on-byo-gpu-nodes.md

Docs update to remove `--skip-gpu-driver-install` node pool tag (to be retired in August) and recommend GA API field instead for BYO GPU nodes with KAITO.

Skip automatic gpu driver installation GA doc update

---

charts/kaito/index.yaml

When onboarding KAITO's helm charts to ArtifactHub, it's complaining that some of them are pointing to an invalid URL:

fix: update helm chart URLs to point to kaito-project instead of Azure

---

website/docs/rag.md

remove rerank options from RAG /query API as upstream llama-index is broken
Resolves #1241 

docs: updage RAG Docs to remove rerank options

---

examples/README.md

doc bug fix. according to [code](https://github.com/kaito-project/kaito/blob/4309784a8468fa7bfe261be9067001d7b09027f9/pkg/workspace/controllers/workspace_controller.go#L589), it is just a val == "True". true is not working

fix doc error kaito.sh/enablelb should be True instead of true

---

.github/workflows/unit-tests.yml
Makefile
charts/kaito/workspace/templates/supported-models-configmap.yaml
hack/compare_model_configs.sh

This will help any client to know the list of models that are supported by Kaito, instead of reading from gh repo.

feat: expose kaito supported models via configmap

---

charts/kaito/workspace/templates/local-csi-driver-ds.yaml
hack/local-csi-driver-charts-sync/local-csi-driver-charts-sync.sh
hack/local-csi-driver-charts-sync/local-csi-driver-charts.diff

Updates local-csi-driver to v0.2.3.
Note: if upgrading there is a manual step needed for capacity-based pod scheduling to continue working:
```console
kubectl -n kube-system delete CSIStorageCapacity -l csi.storage.k8s.io/drivername=localdisk.csi.acstor.io
```
This shouldn't be needed for Kaito since it handles pod scheduling to select specific GPU nodes and doesn't rely on capacity-based scheduling.
Release notes: 
- https://github.com/Azure/local-csi-driver/releases/tag/v0.2.3
- https://github.com/Azure/local-csi-driver/releases/tag/v0.2.2
- https://github.com/Azure/local-csi-driver/releases/tag/v0.2.1

chore: bump local-csi-driver to v0.2.3

---

presets/workspace/inference/text-generation/inference_api.py

This PR resolves the deprecation warnings of the Pydantic library, which you can find in the [CI logs](https://github.com/kaito-project/kaito/actions/runs/16533746572/job/46764334268#step:8:2020):
```python
PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
"generate_kwargs": GenerateKwargs().dict(),
```

fix: resolve pydantic deprecation warnings

---

.github/workflows/deploy-docs.yml
website/docusaurus.config.js

Currently, the search function in the docs site is not working because Algolia wasn't able to verify the ownership of the site domain.
Per https://www.algolia.com/doc/tools/crawler/getting-started/create-crawler/#verify-your-domain, we can verify the domain by adding a `<meta>` HTML tag with specific content. I've added the site verification payload as a repository secret:
**Testing**
Follow-up for #1197

docs: verify docs site with Algolia

---

.github/workflows/preset-image-build.yml
.github/workflows/trivy.yml
Makefile
docker/presets/models/tfs/Dockerfile
docker/ragengine/Dockerfile
docker/ragengine/service/Dockerfile
docker/workspace/Dockerfile

Refactored preset image dockerfile to group os dependencies in one target fo easy scanning
Converted trivy pipeline into matrix strategy
N/A
I am not sure if all of these require scanning, happy to cut down to a subset. Some images I've left out because they are quite large, e.g. the `llm-reference-preset` and `ragservice` images

ci: Expand trivy scanning to other images

---

test/rage2e/rag_test.go

Revert the model used in the rag e2e test back to Phi-3 to avoid the query test failure

chore: Revert the model used in the rag e2e test back to Phi-3

---

.github/workflows/create-release.yaml

Transition release branch prefix from `official/v0.X.Y` to `release-0.X`

ci: update release branch prefix to 'release-'

---

Makefile

Currently, the public docs are updated before we build the helm release. We need to update the docs indicating the helm release is done after the release.

docs: add post release doc update Makefile cmd

---

README.md

Fixed simple typo in Orchestration name
https://github.com/kaito-project/kaito/issues/1390

docs: corrected typo in README.md

---

presets/workspace/dependencies/requirements.txt
presets/workspace/inference/vllm/inference_api.py
presets/workspace/inference/vllm/tests/test_vllm_inference_api.py

feat: offload kv cache to cpu RAM on vllm v1
this PR adds a new parameter `kaito-kv-cache-cpu-memory-utilization` in `KaitoConfig`, by default, it uses 50% free RAM, and user could disable cpu offloading by set as `0` (default is on with 0.5) 
And we don't want to support cpu offloading on vllm v0 since on v1 is the major version now (A10, A100, H100 are all using vllm v1, only T4 is using v0).
This PR also upgrades vllm to 0.9.1 since vllm 0.9.0 + lmcache is not stable, it crashes a lot, and with vllm 0.9.1 + lmcache, there is no crash after dozens of load tests.
- vllm v1 example: https://docs.lmcache.ai/getting_started/quickstart/offload_kv_cache.html
https://docs.vllm.ai/en/stable/configuration/engine_args.html#vllmconfig …

feat: offload kv cache to cpu RAM on vllm v1

---

charts/kaito/workspace/templates/inference-params.yaml
presets/workspace/inference/vllm/inference_api.py

fix: cannot read  kv-cache-cpu-memory-utilization from ConfigMap

fix: cannot read kv-cache-cpu-memory-utilization from ConfigMap

---

presets/workspace/dependencies/requirements.txt

Reverts kaito-project/kaito#1424
[`nvidia-ml-py`](https://pypi.org/project/nvidia-ml-py/) is already added in https://github.com/kaito-project/kaito/pull/1405. https://pypi.org/project/pynvml/ is NOT the correct package to import `pynvml`.

Revert "fix: add missing pynvml package dependency"

---

charts/kaito/workspace/templates/nvidia-device-plugin-ds.yaml
charts/kaito/workspace/values.yaml

fix: add nodeSelector on Linux to avoid crash on Windows node
```
kaito-workspace     kaito-workspace-6db9666b47-xjz7m                      0/1     ImagePullBackOff    0               12d     10.244.4.201   akswgen2000000                      <none>           <none>
kaito-workspace     nvidia-device-plugin-daemonset-nx8d7                  0/1     ImagePullBackOff    0               27d     10.244.4.237   akswgen2000000                      <none>           <none>
```

fix: add nodeSelector on Linux to avoid crash on Windows node

---

CODE_OF_CONDUCT.md

Updated the KAITO Code of Conduct to clarify resources and reporting procedures

docs: fix bits of spellings and revise code of conduct for clarity

---

website/docs/gateway-api-inference-extension.md

Follow-up for #1434. The correct environment variable to enable during istio installation should be `ENABLE_GATEWAY_API_INFERENCE_EXTENSION`.

docs: update istio environment variable in installation step

---

.github/workflows/ragengine-e2e.yaml

add presets/ragengine to rag e2e test workflow so pr's for ragengine ask for the e2e workflow run

fix: add presets/ragengine to rag e2e test workflow

---

charts/kaito/workspace/templates/local-csi-driver-ds.yaml
hack/local-csi-driver-charts-sync/local-csi-driver-charts-sync.sh
hack/local-csi-driver-charts-sync/local-csi-driver-charts.diff

Bump local-csi-driver from v0.2.3 to v0.2.5 by cherry-picking #1406 and then #1440.

chore: bump local-csi-driver v0.2.3 -> v0.2.4 -> v0.2.5 

---

.github/workflows/publish-ragengine-helm-chart.yaml
.github/workflows/publish-workspace-helm-chart.yaml

The current release pipeline can only publish helm charts right after building the controller images. For the upcoming patch release v0.6.1, since it's a helm-chart-only change and there is no change to the controller images, there is no need to trigger the entire release pipeline. Instead, this PR adds the option to only trigger the publish helm charts pipeline only.

release: update helm chart workflows to accept tag input from workflow_dispatch

---

pkg/workspace/manifests/manifests.go
pkg/workspace/manifests/manifests_test.go

https://github.com/kaito-project/kaito/pull/1292 introduced a regression where an empty volumeMount can be appended to the puller container's volume mount if there is no image pull secret defined.
Fixes #1478

fix: ensure a non-empty volumnMount is appended in puller containers

---

website/docs/installation.md
website/docs/rag.md

`helm upgrade [RELEASE] [CHART] [flags]` is the usage and we are missing a release name

fix: helm upgrade --install needs release name

---

docs/proposals/20250918-introduce_inferenceset_autoscaling.md

doc: Introduce a new InferenceSet CRD and Controller for scaling inference workloads automatically, related to https://docs.google.com/presentation/d/1qCpFWuWzvoi5yA2rAa7OhCAUHPRoAmR3-ODJ3SDIgI4/edit?slide=id.g37fd1d8dc1a_0_22#slide=id.g37fd1d8dc1a_0_22

docs: Introduce a new InferenceSet CRD and Controller for scaling inference workloads automatically

---

website/docs/rag.md

the contextWindowSize is required field.
When user follow the documentation they may encounter issue.

docs: Update rag.md

---

pkg/utils/nodeclaim/nodeclaim.go
pkg/utils/nodeclaim/nodeclaim_test.go
pkg/utils/resources/nodes.go
pkg/workspace/resource/node_claim.go
pkg/workspace/resource/node_claim_test.go

The resource ready condition is never set to true after the refactor as it compares the # ready node claims to the # nodes needed rather than the # node claims needed. This breaks as if 1 node is needed and one existing node is brought, it will expect 1 node claim that will never be provisioned as the # nodes is already met.
Fixes #1544 

fix: ResourceReady condition is never set to true for BYO [release-0.7] 

---

presets/ragengine/tests/vector_store/test_base_store.py
presets/ragengine/vector_store/base.py
website/docs/rag-chat-completions-wrapper.md
website/sidebars.js

Both `CONTEXT` and `CONDENSE_PLUS_CONTEXT` Chat types in LlamaIndex use the same CompactAndRefine [response
synthesizers](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/response_synthesizers/compact_and_refine.py)
Which in turn, both `achat` functions would call `response = await synthesizer.asynthesize(message, nodes)` and return an empty response if they have [no
nodes](https://github.com/run-llama/llama_index/blob/8469a034226d20b70a667dc7faf013770716709f/llama-index-core/llama_index/core/response_synthesizers/base.py#L271), all without calling the LLM.
This change checks for the Empty Response from the response synthesizer and validates no source_nodes were found, and if this case is hit, we send the request directly to the …

fix: handle no context found with passthrough to LLM (#1542) [release-0.7] 
